### ISSUE TITLE
battery_last_reported not refreshing.

### ISSUE THREAD

**Issue by radu-boboc** [andrew-codechimp/HA-Battery-Notes#2516]
## System Information

version | core-2024.12.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | Europe/Bucharest
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1555
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 10.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (5.2.10), Terminal & SSH (9.16.0), Mosquitto broker (6.4.1), File editor (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 6
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 16, 2024 at 20:53
-- | --
current_recorder_run | December 20, 2024 at 15:59
estimated_db_size | 725.00 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 1 / 3
local_online | 1 / 1
debug | failed to load: 

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I believe that battery_last_reported  is not being updated, or not in real time or at least not consistently.
I am pressing the buttons, so the information about the device is being refreshed, and I expect to see the battery_last_reported updated with the new timestamp
![batt2](https://github.com/user-attachments/assets/a53e88c1-6c73-4415-b473-a9e430adb843)
As you can see in the attached table, I've made a query to [sensor.*blabla*_battery_plus]>battery_last_reported and all the devices in the table, have the date of the last HA restart. Except one that decided to update itself.
I've pressed all the buttons, at different times, and they were all registered by HA and did something, but this field
Is there a way to force update ? or is it an known issue ?
![batt3](https://github.com/user-attachments/assets/0a4007f6-163d-4e73-9920-a326631de461)

### Reproduction steps

1. restart HA to get even times.
2. press one button
3. wait a minute
4. press another
5. look at the table or do a query for battery_last_reported  
6. the times have not changed.
...

### Debug logs

```text
Not really helpful, but ..
Logs
Search logs
Home Assistant Core
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_lan_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 748, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_lan_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified
2024-12-20 15:59:31.647 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_lan_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.pfsense_obyone_interface_lan_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.lan_upload_mbps'
2024-12-20 15:59:31.647 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states('sensor.pfsense_obyone_interface_lan_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2352, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unavailable'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 631, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2733, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2355, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1909, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_lan_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 748, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_lan_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified
2024-12-20 15:59:31.649 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_lan_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.pfsense_obyone_interface_lan_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.lan_download_mbps'
2024-12-20 15:59:31.650 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states('sensor.pfsense_obyone_interface_wireguard_interface_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2352, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unavailable'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 631, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2733, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2355, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1909, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_wireguard_interface_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 748, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_wireguard_interface_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified
2024-12-20 15:59:31.651 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_wireguard_interface_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.pfsense_obyone_interface_wireguard_interface_inbytes_kilobytes_per_second') | float / 1000) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.wireguard_download_mbps'
2024-12-20 15:59:31.652 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states('sensor.pfsense_obyone_interface_wireguard_interface_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2352, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unavailable'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 631, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2733, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2355, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1909, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_wireguard_interface_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 748, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_wireguard_interface_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified
2024-12-20 15:59:31.654 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.pfsense_obyone_interface_wireguard_interface_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.pfsense_obyone_interface_wireguard_interface_outbytes_kilobytes_per_second') | float / 1000) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.wireguard_upload_mbps'
2024-12-20 15:59:42.327 WARNING (SyncWorker_0) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:00:02.678 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:00:32.994 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:01:23.361 WARNING (SyncWorker_0) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:02:53.644 WARNING (SyncWorker_0) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:04:24.121 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:05:42.009 ERROR (MainThread) [homeassistant.components.script.close] script_Close_blinds: check if relay 1 is on: Error executing script. Invalid data for call_service at pos 2: must contain at least one of entity_id, device_id, area_id, floor_id, label_id.
2024-12-20 16:05:42.009 ERROR (MainThread) [homeassistant.components.script.close] script_Close_blinds: Error executing script. Invalid data for if at pos 2: must contain at least one of entity_id, device_id, area_id, floor_id, label_id.
2024-12-20 16:05:42.010 ERROR (MainThread) [homeassistant.components.automation.press_close_blinds_button_on_somrig_new] Close blinds *: Error executing script. Invalid data for call_service at pos 1: must contain at least one of entity_id, device_id, area_id, floor_id, label_id.
2024-12-20 16:05:42.010 ERROR (MainThread) [homeassistant.components.automation.press_close_blinds_button_on_somrig_new] Error while executing automation automation.press_close_blinds_button_on_somrig_new: must contain at least one of entity_id, device_id, area_id, floor_id, label_id.
2024-12-20 16:05:54.594 WARNING (SyncWorker_6) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:07:24.929 WARNING (SyncWorker_3) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:08:55.149 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:10:25.309 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:11:55.592 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:13:26.099 WARNING (SyncWorker_1) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:14:56.394 WARNING (SyncWorker_6) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:16:26.685 WARNING (SyncWorker_0) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:17:56.849 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:19:27.124 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:20:57.575 WARNING (SyncWorker_3) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:22:27.638 WARNING (SyncWorker_0) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:23:57.741 WARNING (SyncWorker_6) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:25:28.025 WARNING (SyncWorker_6) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:26:58.391 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:28:28.552 WARNING (SyncWorker_3) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:29:58.904 WARNING (SyncWorker_1) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:31:29.365 WARNING (SyncWorker_3) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:32:59.798 WARNING (SyncWorker_6) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:34:29.955 WARNING (SyncWorker_0) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:34:30.987 ERROR (SyncWorker_2) [custom_components.pfsense.pypfsense] Unexpected get_firmware_update_info error err=TimeoutError('The read operation timed out'), type(err)=<class 'TimeoutError'>
2024-12-20 16:36:00.300 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:37:30.767 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:39:00.904 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:40:31.348 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:42:01.470 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:43:31.980 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:45:02.061 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:46:32.284 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:48:02.486 WARNING (SyncWorker_3) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:49:32.915 WARNING (SyncWorker_1) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:51:03.220 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:52:33.451 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:54:03.716 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:55:33.806 WARNING (SyncWorker_3) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:57:04.243 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 16:58:34.338 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 17:00:04.837 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 17:01:34.957 WARNING (SyncWorker_6) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 17:03:05.067 WARNING (SyncWorker_1) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 17:04:35.472 WARNING (SyncWorker_0) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 17:06:05.714 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
2024-12-20 17:07:35.906 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS 192.168.0.13 unable to fetch data "system/info" (no_response)
 Live
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.12.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.0",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Bucharest",
    "os_name": "Linux",
    "os_version": "6.6.66-haos",
    "supervisor": "2024.12.0",
    "host_os": "Home Assistant OS 14.1",
    "docker_version": "27.2.0",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "truenas": {
      "documentation": "https://github.com/tomaae/homeassistant-truenas",
      "version": "0.0.0",
      "requirements": []
    },
    "proxmoxve": {
      "documentation": "https://github.com/dougiteixeira/proxmoxve",
      "version": "3.5.2",
      "requirements": [
        "proxmoxer==2.0.1"
      ]
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.8.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "ingv_centro_nazionale_terremoti": {
      "documentation": "https://github.com/caiosweet/Home-Assistant-custom-components-INGV",
      "version": "2024.08.0",
      "requirements": [
        "aio_quakeml_ingv_centro_nazionale_terremoti_client==0.4"
      ]
    },
    "pfsense": {
      "documentation": "https://github.com/travisghansen/hass-pfsense",
      "version": "0.1.0",
      "requirements": [
        "mac-vendor-lookup>=0.1.11"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "battery_notes": {
      "documentation": "https://andrew-codechimp.github.io/HA-Battery-Notes/",
      "version": "2.7.3",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "battery_notes",
    "name": "Battery Notes",
    "codeowners": [
      "andrew-codechimp"
    ],
    "config_flow": true,
    "documentation": "https://andrew-codechimp.github.io/HA-Battery-Notes/",
    "integration_type": "device",
    "iot_class": "calculated",
    "issue_tracker": "https://github.com/andrew-codechimp/ha-battery-notes/issues",
    "version": "2.7.3",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.09845265500007372
    },
    "01JF8M4K2KPTD6C6M018SVH0J0": {
      "wait_import_platforms": -0.8596171490007691,
      "config_entry_setup": 0.8630831249993207
    },
    "01JF8MGTWK842Q7FYA6G0GQ1GG": {
      "wait_import_platforms": -0.8640467320001335,
      "config_entry_setup": 0.8671321520014317
    },
    "01JF8MHARK2PFP39FYAZ15EXYS": {
      "wait_import_platforms": -0.8668797550017189,
      "config_entry_setup": 0.8703383350002696
    },
    "01JF8MHK510CMN1VN044D3T1A2": {
      "wait_import_platforms": -0.8701156999995874,
      "config_entry_setup": 0.8723421989998315
    },
    "01JF8MJ2N8GGDT5AB0Y2V62X6V": {
      "wait_import_platforms": -0.8722216940004728,
      "config_entry_setup": 0.8745969940009672
    }
  },
  "data": {
    "entry": {
      "created_at": "2024-12-16T21:04:05.288215+00:00",
      "data": {
        "battery_low_template": null,
        "battery_low_threshold": 10,
        "battery_quantity": 1,
        "battery_type": "AAA",
        "device_id": "1d1cc54f230f72ce9d70ee5694aece78",
        "device_name": "IKEA SOMRIG button",
        "manufacturer": "IKEA of Sweden",
        "model": "SOMRIG shortcut button",
        "model_id": [
          null
        ]
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "battery_notes",
      "entry_id": "01JF8MJ2N8GGDT5AB0Y2V62X6V",
      "minor_version": 1,
      "modified_at": "2024-12-16T21:04:05.288219+00:00",
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "integration_discovery",
      "title": "IKEA SOMRIG button",
      "unique_id": "bn_1d1cc54f230f72ce9d70ee5694aece78",
      "version": 2
    },
    "device": {
      "manufacturer": "IKEA of Sweden",
      "model": "SOMRIG shortcut button",
      "model_id": null,
      "hw_version": null
    }
  }
}

**Comment by radu-boboc** [comment]
I named the column Last Seen, but the query is based on battery_last_reported

>  - name: Last Seen
>     data: battery_last_reported
> 

I was thinking, in the terms of: The current battery level was last updated when battery_last_reported
If what you way is true, and the update mechanism is based on when the device wants it to update it, what do you recommend to do in my case?

**Comment by andrew-codechimp** [comment]
If what you are trying to do is get an immediate report of a device offline then battery last reported won't do that. Z2M itself states that battery levels can take up to 24 hours to update, which is why the example notifications in battery notes are based on days not reported.

**Comment by radu-boboc** [comment]
I was trying to understand when was the battery last updated. If it is 10 days ago, the last reading is old and maybe it is already dead, but if it is a recent report, than I can take the battery level as accurate.

I just saw another problem:
![image](https://github.com/user-attachments/assets/4300ee9f-5d9b-4f2b-906e-cc081ef99790)
After sleeping I noticed that two of my battery reports turned to NaN even though they were pressed at around the same time as the others ~22:00.
Just before taking the screenshot, one of them turned to 0% batt level, but the question remains, why the NaN reporting? and why  only on two devices?

**Comment by andrew-codechimp** [comment]
That's exactly what the automation example for battery last reported is for, I have mine set to 5 days which although not instant spots those that died suddenly, which my plant sensors tend to do. 
The nan is probably when the device flips to unknown or unavailable temporarily, a few of my sensors do that. Your template query isn't handling unknown or unavailable.

**Comment by radu-boboc** [comment]
Not gonna have time during holidays, but after I want to take a look at that automation example you mentioned above.
Merry Christmas, and thank you for creating this!

**Comment by andrew-codechimp** [comment]
Thanks and Merry Christmas to you.
I'll close this issue as I'm sure the automations will give you a better understanding of what's possible with the last_reported.

**Comment by radu-boboc** [comment]
I am super sorry to re-open this, but where is the automation that you are referring to ? I am not sure where to search for it.

**Comment by andrew-codechimp** [comment]
No problem, it's in the docs community section
https://andrew-codechimp.github.io/HA-Battery-Notes/community/#battery-not-reported
There's also a blueprint if you prefer
https://andrew-codechimp.github.io/HA-Battery-Notes/community/#battery-not-reported_1

Note the requirement to trigger the automation by a schedule, events are a bit odd if you've not used them much.
https://andrew-codechimp.github.io/HA-Battery-Notes/community/#check-battery-last-reported-daily
