### ISSUE TITLE
Cannot download from HACS

### ISSUE THREAD

**Issue by tebrown** [andrew-codechimp/HA-Battery-Notes#634]
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4792
Installed Version | 1.34.0
Stage | running
Available Repositories | 1457
Downloaded Repositories | 44
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 12, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-8.ui.nabu.casa
certificate_status | ready
instance_id | 02146cf3609d4a398e6394e587210b51
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 125.3 GB
disk_used | 57.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Advanced SSH & Web Terminal (17.0.4), Mosquitto broker (6.4.0), Z-Wave JS (0.4.3), rtlamr2mqtt (2.3.4), WeatherFlow to MQTT (3.2.2), Studio Code Server (5.15.0), ESPHome (2023.12.8), Matter Server (5.0.4), Music Assistant BETA (2.0.0b83), openWakeWord (1.8.2), Whisper (1.0.2), Piper (1.4.0), Fusion (2024.1.6), Govee to MQTT Bridge (2024.01.21-33e8cd7c)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 22
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 12, 2024 at 3:55 PM
-- | --
current_recorder_run | January 21, 2024 at 6:02 PM
estimated_db_size | 1026.83 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When HACS tries to download the zip, it uses this URL:
`https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/1.4.1/battery_notes.zip`

However, the actual URL is 
`https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/tags/1.4.1/battery-notes.zip`

### Reproduction steps

1. Open HACS
2. Find Battery Notes
3. Click Battery Notes
4. Click Download
5. Get 'Unknown Error'

### Debug logs

```text
-01-21 18:04:10.666 DEBUG (MainThread) [custom_components.hacs] <Integration andrew-codechimp/HA-Battery-Notes> Getting documentation for version=1.4.1,filename=README.md
2024-01-21 18:04:10.666 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/andrew-codechimp/HA-Battery-Notes/1.4.1/README.md
2024-01-21 18:04:10.786 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-01-21 18:04:10.786 DEBUG (MainThread) [custom_components.hacs] <Integration andrew-codechimp/HA-Battery-Notes> Local path is set to /config/custom_components/battery_notes
2024-01-21 18:04:10.786 DEBUG (MainThread) [custom_components.hacs] <Integration andrew-codechimp/HA-Battery-Notes> Remote path is set to custom_components/battery_notes
2024-01-21 18:04:10.786 DEBUG (MainThread) [custom_components.hacs] <Integration andrew-codechimp/HA-Battery-Notes> Version to install: 1.4.1
2024-01-21 18:04:10.786 DEBUG (MainThread) [custom_components.hacs] Trying to download https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/1.4.1/battery-notes.zip
2024-01-21 18:04:10.919 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/1.4.1/battery-notes.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/1.4.1/battery-notes.zip
2024-01-21 18:04:10.920 ERROR (MainThread) [custom_components.hacs] <Integration andrew-codechimp/HA-Battery-Notes> Failed to download https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/tags/1.4.1/battery-notes.zip
2024-01-21 18:04:10.920 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140034523800768] Error handling message: Unknown error (unknown_error) Travis from 127.0.0.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
2024-01-21 18:04:12.595 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://192.168.10.2:5000/api/stats: Cannot connect to host 192.168.10.2:5000 ssl:default [Connect call failed ('192.168.10.2', 5000)]
2024-01-21 18:04:16.294 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2024-01-21 18:04:20.999 INFO (MainThread) [pyhap.hap_protocol] ('192.168.10.61', 61451): Connection made to  2021 RAV4 PRIME XSE AWD SUV
2024-01-21 18:04:47.287 WARNING (SyncWorker_11) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061:
```

### Diagnostics dump

N/A

**Comment by andrew-codechimp** [comment]
Hi, the download URL https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/1.4.1/battery_notes.zip should work fine, there's a file there if you try and manually download it.
HACS creates the path to the download file automatically, I do not control this.

The warning "Unverified HTTPS request is being made to host '192.168.10.1'" looks like it's routing via something internal and could be stopping HACS from downloading.

Have you tried downloading another integration via HACS?
I'd suggest ensuring you have HACS up to date.

**Comment by jonalbr** [comment]
It seems that HACS expect the zip file to be named "battery-notes.zip" instead of "battery_notes.zip". I guess if you would name the release accordingly this would solve the problem. 

My log report:

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:730
Integration: HACS (documentation, issues)
First occurred: 11:02:29 (1 occurrences)
Last logged: 11:02:29

Download failed - Got status code 404 when trying to download https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/1.4.1/battery-notes.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/1.4.1/battery-notes.zip

**Comment by andrew-codechimp** [comment]
Now that's bizarre, I've always had that mismatch looking at the history but it's never been an issue before given how many people are using HACS to get this.
I've fixed the mismatch and put in a duplicate zip with the correct name which should hopefully fix it.
Let me know how you get on.

**Comment by jsb2092** [comment]
> Hi, the download URL https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/1.4.1/battery_notes.zip should work fine, there's a file there if you try and manually download it. HACS creates the path to the download file automatically, I do not control this.
> 
> The warning "Unverified HTTPS request is being made to host '192.168.10.1'" looks like it's routing via something internal and could be stopping HACS from downloading.
> 
> Have you tried downloading another integration via HACS? I'd suggest ensuring you have HACS up to date.

I was sitting there with him when he tried this, other integrations worked.  The issue was HACS was trying to download the file with the underscore, not the - as previously stated.

**Comment by jonalbr** [comment]
Fixed for me

**Comment by tebrown** [comment]
Can confirm.  Fixed!  Thank you!
